micronaut:
  application:
    name: carrosGrpc
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/carrosgrpc
    driverClassName: org.postgresql.Driver
    username: carros
    password: carros
    schema-generate: CREATE_DROP
    dialect: POSTGRES

jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa.default.properties.hibernate.show_sql: true
jpa.default.properties.hibernate.format_sql: true

